### ISSUE TITLE
[Regression] Error in freshness tests on Redshift external tables (DBT Cloud)

### ISSUE THREAD

**Issue by romj** [dbt-labs/dbt-redshift#757]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Freshness tests on external table do not run since I've upgraded from 1.6 to 1.7 on DBT cloud

The error is: 
``` 
Compilation Error in source customer_io_delivery_contents (models/staging/external_tables/external_tables_schema.yml)
 Got an invalid result from "get_relation_last_modified" macro: []
```

### Expected/Previous Behavior

Freshness tests work fine in 1.6

### Steps To Reproduce

1. You need a redshift cluster with an external table
2. Define a freshness test
3. run a freshness test

### Relevant log output

```shell
2024-04-04 09:34:38.389139 (Thread-1 (worker)): 09:34:38  Began running node source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents
2024-04-04 09:34:38.389736 (Thread-1 (worker)): 09:34:38  5 of 78 START freshness of external_raw_customer_io.customer_io_delivery_contents  [RUN]
2024-04-04 09:34:38.390512 (Thread-1 (worker)): 09:34:38  Re-using an available connection from the pool (formerly source.stonly_analytics.ads_google.ad_performance_reports, now source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents)
2024-04-04 09:34:38.390992 (Thread-1 (worker)): 09:34:38  Began compiling node source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents
2024-04-04 09:34:38.391546 (Thread-1 (worker)): 09:34:38  Timing info for source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents (compile): 09:34:38.391378 => 09:34:38.391382
2024-04-04 09:34:38.392045 (Thread-1 (worker)): 09:34:38  Began executing node source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents
2024-04-04 09:34:38.392986 (Thread-1 (worker)): 09:34:38  Using redshift connection "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"
2024-04-04 09:34:38.393486 (Thread-1 (worker)): 09:34:38  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: BEGIN
2024-04-04 09:34:38.393976 (Thread-1 (worker)): 09:34:38  Opening a new connection, currently in state closed
2024-04-04 09:34:38.394551 (Thread-1 (worker)): 09:34:38  Redshift adapter: Establishing connection using ssl with `sslmode` set to 'prefer'.To connect without ssl, set `sslmode` to 'disable'.
2024-04-04 09:34:38.395052 (Thread-1 (worker)): 09:34:38  Redshift adapter: Connecting to redshift with username/password based auth...
2024-04-04 09:34:39.074450 (Thread-1 (worker)): 09:34:39  SQL status: SUCCESS in 1.0 seconds
2024-04-04 09:34:39.075564 (Thread-1 (worker)): 09:34:39  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: COMMIT
2024-04-04 09:34:39.076465 (Thread-1 (worker)): 09:34:39  Using redshift connection "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"
2024-04-04 09:34:39.077219 (Thread-1 (worker)): 09:34:39  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: COMMIT
2024-04-04 09:34:39.243804 (Thread-1 (worker)): 09:34:39  SQL status: SUCCESS in 0.0 seconds
2024-04-04 09:34:39.248409 (Thread-1 (worker)): 09:34:39  Using redshift connection "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"
2024-04-04 09:34:39.248978 (Thread-1 (worker)): 09:34:39  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: BEGIN
2024-04-04 09:34:39.332892 (Thread-1 (worker)): 09:34:39  SQL status: SUCCESS in 0.0 seconds
2024-04-04 09:34:39.333517 (Thread-1 (worker)): 09:34:39  Using redshift connection "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"
2024-04-04 09:34:39.334014 (Thread-1 (worker)): 09:34:39  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: /* {"app": "dbt", "dbt_version": "1.7.11", "profile_name": "user", "target_name": "prod", "node_id": "source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents"} */
select
            ns.nspname as "schema",
            c.relname as identifier,
            max(qd.start_time) as last_modified,
            getdate() as snapshotted_at
        from pg_class c
        join pg_namespace ns
            on ns.oid = c.relnamespace
        join sys_query_detail qd
            on qd.table_id = c.oid
        where qd.step_name = 'insert'
        and ((
                    upper(ns.nspname) = upper('external_raw_data')
                and upper(c.relname) = upper('ci_delivery_contents_customer_io')
                ))
        group by 1, 2, 4

2024-04-04 09:37:27.392694 (Thread-1 (worker)): 09:37:27  SQL status: SUCCESS in 168.0 seconds
2024-04-04 09:37:27.394203 (Thread-1 (worker)): 09:37:27  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: ROLLBACK
2024-04-04 09:37:27.561375 (Thread-1 (worker)): 09:37:27  On source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents: Close
2024-04-04 09:37:27.562594 (Thread-1 (worker)): 09:37:27  Timing info for source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents (execute): 09:34:38.392422 => 09:37:27.562397
2024-04-04 09:37:27.564406 (Thread-1 (worker)): 09:37:27  Compilation Error in source customer_io_delivery_contents (models/staging/external_tables/external_tables_schema.yml)
  Got an invalid result from "get_relation_last_modified" macro: []
2024-04-04 09:37:27.565081 (Thread-1 (worker)): 09:37:27  5 of 78 ERROR freshness of external_raw_customer_io.customer_io_delivery_contents  [[31mERROR[0m in 169.17s]
2024-04-04 09:37:27.565769 (Thread-1 (worker)): 09:37:27  Finished running node source.stonly_analytics.external_raw_customer_io.customer_io_delivery_contents
```

### Environment

```markdown
- OS: DBT Cloud
- Python: DBT Cloud
- dbt (working version): 1.6
- dbt (regression version): 1.7
```

### Which database adapter are you using with dbt?

redshift

**Comment by dataders** [comment]
@romj thanks for taking the time to open up this bug report, not to mention the helpful details. I was indeed able to reproduce the error you give, but only when a `loaded_at_field` was not specified. when it was specified, it the freshness test ran as intended.

My guess is that your the freshness tests defined on your external table did not specify the `loaded_at_field`, because when I do so with `dbt-redshift==1.6.12`, dbt tells me "Nothing to do" when I run `dbt source freshness`.

what's happening is a [behavior change in dbt Core 1.7.0](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.7#behavior-changes) related to `source freshness` 
<details><summary>Excerpt from docs page</summary>
<p>

> dbt Core v1.7 expands the amount of sources you can configure freshness for. Previously, freshness was limited to sources with a `loaded_at_field`; now, freshness can be generated from warehouse metadata tables when available.
>
> As part of this change, the `loaded_at_field` is no longer required to generate source freshness. If a source has a freshness: block, dbt will attempt to calculate freshness for that source:
> - If a `loaded_at_field` is provided, dbt will calculate freshness via a select query (previous behavior).
> - If a `loaded_at_field` is not provided, dbt will calculate freshness via warehouse metadata tables when possible (new behavior).
>
> This is a relatively small behavior change, but worth calling out in case you notice that dbt is calculating freshness for more sources than before. To exclude a source from freshness calculations, you have two options:
> 
> - Don't add a `freshness:` block.
> - Explicitly set `freshness: null`

</p>
</details> 

source freshness checks without a `loaded_at_field` field were not supported prior to `1.7.0`, however, no error message was thrown, rather the freshness test was skipped. Now in `1.7` and beyond, no specification of `loaded_at_field` is a feature and your previously-skipped freshness tests were now executed (but failing, loudly).


### remediation

the immediate "workaround" is that @romj removes any freshness check defined on an external table in your project

However, there might also be work to more clearly communicate this behavior change moving forward. Certainly in the docs!



<details><summary>

### reproduction

s</summary>

#### prerequisites

- a Redshift cluster in `us-east-2`
- the below `sources.yml` in your project
- the dbt-external-tables package installed

#### commands

```
to create the external table
dbt run-operation dbt_external_tables.stage_external_sources --vars 'ext_full_refresh: true' --args 'select: redshift_external.orders_csv'
# to ensure the table is properly defined and accesible
dbt show --inline "SELECT x.* FROM dbt_external_tables_integration_tests_redshift_spectrum.orders_csv x"                                  
```

#### sources.yml

```yml
# sources.yml
version: 2

sources:
  - name: redshift_external
    schema: "redshift_spectrum"
    loader: S3

    tables:

      - name: orders_csv
        external:
          row_format: serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
          table_properties: "('skip.header.line.count'='1')"
          location: s3://jaffle-us-east-2/manifest3.json
        freshness:
          error_after:
            count: 1
            period: day
        # loaded_at_field: "order_date::timestamp"
        columns:
          - name: id
            data_type: int
          - name: user_id
            data_type: int
          - name: order_date
            data_type: date
          - name: status
            data_type: varchar(64)

```

<p>



</p>
</details>

**Comment by dataders** [comment]
@romj happy to discuss this further, but for now I'm going to close this in favor of https://github.com/dbt-labs/dbt-core/issues/9979

**Comment by romj** [comment]
Thanks for looking into it! I confirm that your suggestion worked - adding loaded_at_field param fixed the test

Jean
